# Generated by Django 3.0.4 on 2020-06-07 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0003_auto_20200607_1423'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='score',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
