# Generated by Django 3.0.4 on 2020-06-07 08:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0005_selection_contents'),
    ]

    operations = [
        migrations.AddField(
            model_name='problembox',
            name='score',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='problem',
            name='tests',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='problem_tests', to='interview.Tests'),
        ),
    ]
