# Generated by Django 3.0.4 on 2020-06-07 09:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0007_testbox_selectionscore'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobfairs',
            name='active',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='problembox',
            name='score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='problembox',
            name='selectionAnswer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='problem_box_selection', to='interview.Selection'),
        ),
    ]
