# Generated by Django 3.0.4 on 2020-06-09 01:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0008_auto_20200607_1724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problembox',
            name='selectionAnswer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='problem_box_selection', to='interview.Selection'),
        ),
    ]
