# Generated by Django 3.0.4 on 2020-06-09 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0009_auto_20200609_0920'),
    ]

    operations = [
        migrations.AddField(
            model_name='testbox',
            name='isCorrect',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
