# Generated by Django 3.0.4 on 2020-06-10 02:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0010_testbox_iscorrect'),
    ]

    operations = [
        migrations.AddField(
            model_name='problembox',
            name='testBox',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='problem_box_test_box', to='interview.TestBox'),
        ),
    ]
