# Generated by Django 3.0.4 on 2020-06-21 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exhibition', '0002_auto_20200621_1705'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='type',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
